### PR TITLE
Fix path change issue when loading data into ARTwarp

### PR DESCRIPTION
**Pull request by RohanK22**
It is a very simple fix that just saves the current path in a global variable before loading the data, and after the data is loaded it restores the current working directory back to the ARTwarp code directory.

### CODE REVIEW

**Comment by douggillespie** [comment]
Why don't you leave the path as it is, and use full file path names to load the data ? My memory is that it switches the working directory to the data folder, but if you used full file paths, that wouldn't be necessary.

**Comment by RohanK22** [comment]
I think the changes should load the ctr files by using their full path names instead of switching the current directory. I have removed the unnecessary cd(path) commands in the code.

**Comment by douggillespie** [comment]
Sorry for not getting to this earlier. this is the right approach, however Matlab has a nice 'fullfile' function which will join the bits of the path together, rather than using append like you have done: test=csvread(append(DATA(c1).folder, '/', DATA(c1).name)

**Comment by RohanK22** [comment]
Ok. I've changed it to use the 'fullfile' function instead.

**Comment by RohanK22** [comment]
@douggillespie , @vmjanik , can this be merged now?

**Pull request merged**
